# Generated by Django 3.1 on 2020-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.TextField(choices=[('DOC', 'Docs'), ('MD', 'Markdown')]),
        ),
    ]
