# Generated by Django 3.1 on 2020-12-20 17:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/files/'), upload_to='files'),
        ),
    ]
