# Generated by Django 3.1 on 2020-12-20 20:07

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20201220_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(),
        ),
    ]
