# Generated by Django 3.1 on 2020-12-20 20:16

import django.core.files.storage
from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20201220_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/AOKov/PycharmProjects/todocs/files/')),
        ),
    ]
