# Generated by Django 3.1 on 2020-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20201220_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.TextField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
