# Generated by Django 3.1 on 2020-12-21 17:36

from django.db import migrations, models
import django_hashedfilenamestorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_auto_20201221_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=django_hashedfilenamestorage.storage.HashedFilenameFileSystemStorage(location='/Users/AOKov/PycharmProjects/todocs/files/'), upload_to=''),
        ),
    ]
