# Generated by Django 3.1.5 on 2021-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_collaboration_access_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique collaboration'),
        ),
    ]
